[general]
data_dir=%app%\..\Data
cache_dir=%app%\..\Cache
command_line=--disable-features=msCopilotMode2,msOmniboxFocusRingRoundEmphasize --enable-features=msForceNoRoundedCornerAndMargin 
ignore_policies=0
win32k=0

[tabs]
; Click on the currently active tab to scroll to the top of the page (like Safari/Cốc Cốc)
; Set to 1 to enable
click_tab_scroll_top=0
